sudo: require
services:
    - docker

before_install:
    - docker build -t cfaguilera20/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run cfaguilera20/react-test npm test -- --coverage

after_success:
    - docker build -t cfaguilera20/complex-client ./client
    - docker build -t cfaguilera20/complex-nginx ./nginx
    - docker build -t cfaguilera20/complex-server ./server
    - docker build -t cfaguilera20/complex-worker ./worker
    # Login in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push cfaguilera20/complex-client
    - docker push cfaguilera20/complex-nginx
    - docker push cfaguilera20/complex-server
    - docker push cfaguilera20/complex-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: docker-complex-aws
    env: DockerComplexAws-env
    bucket_name: elasticbeanstalk-us-east-1-330478549731
    bucket_path: docker-complex-aws
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
